name: publish

on:
  release:
    types: [ published ]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run tests
        run: ./gradlew test
  publish:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set output
        id: vars
        run: |
          echo ${GITHUB_REF_NAME:1} 
          echo ::set-output name=version::${GITHUB_REF_NAME:1}
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Prepare to publish
        run: |
          echo '${{secrets.ORG_GRADLE_PROJECT_SIGNING_KEY}}' | base64 -d > secret.kbx
      - name: Deploy Snapshot
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
        with:
          arguments: publish -Psigning.secretKeyRingFile=secret.kbx -Psigning.keyId=${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY_ID }} -Psigning.password=${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }} -PossrhUsername=${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }} -PossrhPassword=${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
